server:
  port: 9527

eureka:
  instance:
    hostname: CLOUD-GATEWAY-SERVICE
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用为服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          filters:
            - AddRequestParameter=X-Request-Id,1024
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
#            - After=2020-06-01T20:56:21.473+08:00[Asia/Shanghai]
#            - Cookie=username,Administrator
#            - Header=X-Request-Id, \d+

        - id: payment_route3
          uri: http://news.baidu.com/guoji
            #            uri: lb://cloud-payment-service
          predicates:
            - Path=/guoji

        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/feign/** #断言,路径相匹配的进行路由
            #              - After=2020-03-12T15:44:15.064+08:00[Asia/Shanghai]
            #- Cookie=username,eiletxie   #带Cookie，并且username的值为eiletxie
            #- Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式
